### PR TITLE
feat: k8s policies sub types support

### PR DESCRIPTION
**Pull request by chen-keinan**
feat: k8s policies sub types support

- Related https://github.com/aquasecurity/trivy/issues/5679
- Related https://github.com/aquasecurity/defsec/pull/1502

### CODE REVIEW

**Comment by chen-keinan** [comment]
@simar7 test and dependencies are updated

**Comment by simar7** [comment]
> @simar7 test and dependencies are updated

Looks the linter is failing.

**Comment by chen-keinan** [comment]
@simar7 PR is ready

**Comment by simar7** [comment]
@chen-keinan could you please rebase this again?

**Review by simar7 — APPROVED** [review]

**Pull request merged**
