### PR TITLE
feat(terraform): add support for AWS provider block

### PR DESCRIPTION
**Pull request by nikpivkin**
Closes https://github.com/aquasecurity/trivy/issues/5459

### Related PRs:
- [x] https://github.com/aquasecurity/defsec/pull/1493
- [x] https://github.com/aquasecurity/defsec/pull/1498

Ref:
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs#argument-reference
- https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/provider/provider.go

### CODE REVIEW

**Comment by nikpivkin** [comment]
@simar7 Since the json schema is built on the state structure field names, the provider blocks will be defined as a service named [providers](https://github.com/aquasecurity/trivy-iac/pull/50/files#diff-89cda47c1df114fb5439afa587f1a6e8a0be86f8b8e38c8e28051262e25dc90cR1305). Will this confuse users when defining Rego policies?

**Comment by simar7** [comment]
> @simar7 Since the json schema is built on the state structure field names, the provider blocks will be defined as a service named [providers](https://github.com/aquasecurity/trivy-iac/pull/50/files#diff-89cda47c1df114fb5439afa587f1a6e8a0be86f8b8e38c8e28051262e25dc90cR1305). Will this confuse users when defining Rego policies?

Hmm, what if we define it at the `aws.AWS{}` level rather than a struct within a struct (what you have in this PR)? 

Another option could be calling it `meta`. It implies that it's not an actual service as naming it "providers" is a little awkward.

**Comment by nikpivkin** [comment]
@simar7 you mean add terraform providers [here](https://github.com/aquasecurity/defsec/blob/master/pkg/state/state.go#L19C7-L19C7)?

**Comment by nikpivkin** [comment]
@simar7 How about naming this field as  meta.tfproviders (tfproviders inside the meta structure)? so that users realise they are dealing with a terraform provider

**Comment by simar7** [comment]
> @simar7 How about naming this field as `meta.tfproviders` (tfproviders inside the meta structure)? so that users realise they are dealing with a terraform provider

Could you give an example? My assumption was that each cloud can have a meta field, so the policies would look something like the following:

` foo = input.aws.meta.bar[_]` or `foo =  input.gcp.meta.bar[_]`.

**Comment by nikpivkin** [comment]
@simar7 that's what I meant: `arg = input.aws.meta.tfproviders.arg[_]`

**Comment by simar7** [comment]
> @simar7 That's what I meant: `arg = input.aws.meta.tfproviders.arg[_]`

But cloud args aren't related to Terraform. For instance tags is a property of AWS Cloud not something specific to Terraform right? So in short, adding `.tfproviders` seems unnecessary. WDYT?

**Comment by nikpivkin** [comment]
@simar7 You're right, the [tags](https://docs.aws.amazon.com/tag-editor/latest/userguide/tagging.html) are not specific to terraform. But I have added support for [AWS provider attributes](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#argument-reference) that are specified in the provider [configuration block](https://developer.hashicorp.com/terraform/language/providers/configuration).

**Comment by simar7** [comment]
> @simar7 You're right, the [tags](https://docs.aws.amazon.com/tag-editor/latest/userguide/tagging.html) are not specific to terraform. But I have added support for [AWS provider attributes](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#argument-reference) that are specified in the provider [configuration block](https://developer.hashicorp.com/terraform/language/providers/configuration).

cool, that makes sense then!

**Review by simar7 — APPROVED** [review]

**Pull request merged**
