### PR TITLE
fix(gke): Remove `pod-security-policy-config` check

### PR DESCRIPTION
**Pull request by JohnTitor**
Remove the check as part of https://github.com/aquasecurity/trivy/issues/5011

Related PRs
- [ ] https://github.com/aquasecurity/defsec/pull/1492

### CODE REVIEW

**Review by simar7 — APPROVED** [review]
@nikpivkin could you take a look as well?

**Comment by nikpivkin** [comment]
@simar7 I think we should first remove the [PodSecurityPolicy](https://github.com/aquasecurity/defsec/blob/bea2dc82c0603576c17636c54640dbc39920a0ea/pkg/providers/google/gke/gke.go#L20C3-L20C3) field from defsec and the rule from [trivy-policies](https://github.com/search?q=repo%3Aaquasecurity%2Ftrivy-policies%20PodSecurityPolicy&type=code) to update the schema and documentation.

**Comment by nikpivkin** [comment]
I opened PR https://github.com/aquasecurity/defsec/pull/1492. 

I checked, and found that the policies do not use this field when scanning GKE. But Pod Security Policies are [checked](https://github.com/aquasecurity/trivy-policies/blob/275c474642c9ce66131245ae4134681c8b6f63af/rules/kubernetes/policies/cisbenchmarks/apiserver/security_context_deny_plugin.rego#L2) when scanning k8s. I think we should create a separate issue for that. Wdyt?

**Comment by simar7** [comment]
> I opened PR [aquasecurity/defsec#1492](https://github.com/aquasecurity/defsec/pull/1492).
> 
> @simar7 I checked, and found that the policies do not use this field when scanning GKE, so they don't need to be updated. But Pod Security Policies are [checked](https://github.com/aquasecurity/trivy-policies/blob/275c474642c9ce66131245ae4134681c8b6f63af/rules/kubernetes/policies/cisbenchmarks/apiserver/security_context_deny_plugin.rego#L2) when scanning k8s. I think we should create a separate issue for that. Wdyt?

@chen-keinan what do you think? Should we deprecate PSP altogether as mentioned above?

**Comment by chen-keinan** [comment]
> > I opened PR [aquasecurity/defsec#1492](https://github.com/aquasecurity/defsec/pull/1492).
> > @simar7 I checked, and found that the policies do not use this field when scanning GKE, so they don't need to be updated. But Pod Security Policies are [checked](https://github.com/aquasecurity/trivy-policies/blob/275c474642c9ce66131245ae4134681c8b6f63af/rules/kubernetes/policies/cisbenchmarks/apiserver/security_context_deny_plugin.rego#L2) when scanning k8s. I think we should create a separate issue for that. Wdyt?
> 
> @chen-keinan what do you think? Should we deprecate PSP altogether as mentioned above?

its true `psp` is check with k8s however I assume if you use terraform scanner only it will not

**Comment by nikpivkin** [comment]
@chen-keinan trivy-iac also scans k8s

**Comment by chen-keinan** [comment]
> @chen-keinan trivy-iac also scans k8s

isn't the rules above are made for terraform files ?

**Comment by nikpivkin** [comment]
@simar7 [This](https://github.com/aquasecurity/trivy-policies/blob/275c474642c9ce66131245ae4134681c8b6f63af/rules/kubernetes/policies/cisbenchmarks/apiserver/security_context_deny_plugin.rego#L2) policy is used when scanning k8s and helm.

**Comment by chen-keinan** [comment]
> @chen-keinan [This](https://github.com/aquasecurity/trivy-policies/blob/275c474642c9ce66131245ae4134681c8b6f63af/rules/kubernetes/policies/cisbenchmarks/apiserver/security_context_deny_plugin.rego#L2) policy is used when scanning k8s and helm.

@nikpivkin so maybe I'm misunderstanding which policies you suggested to removed ?

**Comment by nikpivkin** [comment]
@chen-keinan PodSecurityPolicy was [removed](https://kubernetes.io/docs/concepts/security/pod-security-policy/) from Kubernetes in v1.25, but it is used in k8s policy. That's why I suggested creating a issue for it,  but not removing the rule.

**Comment by chen-keinan** [comment]
> @chen-keinan PodSecurityPolicy was [removed](https://kubernetes.io/docs/concepts/security/pod-security-policy/) from Kubernetes in v1.25, but it is used in k8s [policy](https://github.com/aquasecurity/trivy-policies/blob/275c474642c9ce66131245ae4134681c8b6f63af/rules/kubernetes/policies/cisbenchmarks/apiserver/security_context_deny_plugin.rego#L2). That's why I suggested creating a issue for it, but not removing the rule.

I see , thanks for clarifications

**Comment by simar7** [comment]
> I opened PR [aquasecurity/defsec#1492](https://github.com/aquasecurity/defsec/pull/1492).
> 
> @simar7 I checked, and found that the policies do not use this field when scanning GKE, so they don't need to be updated. But Pod Security Policies are [checked](https://github.com/aquasecurity/trivy-policies/blob/275c474642c9ce66131245ae4134681c8b6f63af/rules/kubernetes/policies/cisbenchmarks/apiserver/security_context_deny_plugin.rego#L2) when scanning k8s. I think we should create a separate issue for that. Wdyt?

As for the separate issue, we should do that for those policies as they don't seem to use these fields (but a separate k8s rego library).

**Comment by simar7** [comment]
> > @chen-keinan PodSecurityPolicy was [removed](https://kubernetes.io/docs/concepts/security/pod-security-policy/) from Kubernetes in v1.25, but it is used in k8s [policy](https://github.com/aquasecurity/trivy-policies/blob/275c474642c9ce66131245ae4134681c8b6f63af/rules/kubernetes/policies/cisbenchmarks/apiserver/security_context_deny_plugin.rego#L2). That's why I suggested creating a issue for it, but not removing the rule.
> 
> I see , thanks for clarifications

I've created https://github.com/aquasecurity/trivy/issues/5541 to track it.

**Pull request merged**
